"""Local filesystem adapter for the :class:`~document_service.domain.storage.FileStorage` port.

Objects live under a configured storage root, addressed by the random key generated by the domain
(never by the client's filename). Two independent defences keep a request inside that root: the key
is validated against a strict pattern before any path is built, and the resolved path is then
checked to be contained in the resolved root — so even a future malformed key or a symlinked
directory cannot escape (docs/06 "path traversal protection").

Filesystem calls are blocking, so each of them runs in a worker thread; the service therefore
streams large uploads and downloads without holding the event loop.
"""

from __future__ import annotations

import asyncio
from collections.abc import AsyncIterator
from pathlib import Path
from typing import BinaryIO

from document_service.domain.storage import (
    STREAM_CHUNK_SIZE,
    StorageKeyError,
    StorageLimitExceededError,
    StoredObjectMissingError,
    validate_storage_key,
)

BACKEND_NAME = "local"


class LocalFileStorage:
    """Stores document bytes in a directory tree on a local (or network-mounted) filesystem.

    Attributes:
        root: The resolved storage root; every object path must remain inside it.
    """

    def __init__(self, root: Path) -> None:
        """Initialize the adapter and ensure the storage root exists.

        Args:
            root: Directory that holds stored objects. Created (with parents) when missing; in the
                compose stack it is a persistent volume, so a restart does not lose files.
        """
        self.root = Path(root).resolve()
        self.root.mkdir(parents=True, exist_ok=True)

    @property
    def backend_name(self) -> str:
        """Return the backend identifier recorded on each document.

        Returns:
            The constant ``local`` (ADR-014).
        """
        return BACKEND_NAME

    def _path_for(self, key: str) -> Path:
        """Resolve the absolute path of a storage key, refusing anything outside the root.

        Args:
            key: The storage key.

        Returns:
            The absolute path of the stored object.

        Raises:
            StorageKeyError: If the key is malformed, or if the resolved path would fall outside
                the storage root (defence in depth behind the key-pattern check).
        """
        validate_storage_key(key)
        # ``strict=False``: the object may not exist yet (writes) and symlinked parents are still
        # resolved, so containment is checked against the real location.
        candidate = (self.root / key).resolve(strict=False)
        if not candidate.is_relative_to(self.root):
            raise StorageKeyError(f"storage key escapes the storage root: {key!r}")
        return candidate

    async def save(self, key: str, chunks: AsyncIterator[bytes], max_bytes: int) -> int:
        """Stream chunks into a new object, enforcing the size limit.

        The object is written directly to its final path; on any failure — including the size limit
        — the partial file is removed, so a rejected upload never leaves readable bytes behind. The
        caller records ``UPLOAD_FAILED`` metadata for the same reason.

        Args:
            key: The storage key to write to.
            chunks: The content, as an async iterator of byte chunks.
            max_bytes: The maximum number of bytes accepted.

        Returns:
            The number of bytes written.

        Raises:
            StorageKeyError: If the key is malformed.
            StorageLimitExceededError: If the content exceeds ``max_bytes``.
        """
        path = self._path_for(key)
        await asyncio.to_thread(path.parent.mkdir, parents=True, exist_ok=True)
        written = 0
        handle: BinaryIO = await asyncio.to_thread(path.open, "wb")
        try:
            async for chunk in chunks:
                if not chunk:
                    continue
                written += len(chunk)
                if written > max_bytes:
                    raise StorageLimitExceededError(
                        f"upload exceeds the maximum of {max_bytes} bytes"
                    )
                await asyncio.to_thread(handle.write, chunk)
        except BaseException:
            # Includes cancellation: a client that disconnects mid-upload must not leave an object.
            await asyncio.to_thread(handle.close)
            await self.delete(key)
            raise
        await asyncio.to_thread(handle.close)
        return written

    async def open_stream(self, key: str) -> AsyncIterator[bytes]:
        """Stream a stored object in bounded chunks.

        Args:
            key: The storage key to read.

        Returns:
            An async iterator over the stored bytes.

        Raises:
            StorageKeyError: If the key is malformed.
            StoredObjectMissingError: If the object is absent from the backend.
        """
        path = self._path_for(key)
        if not await asyncio.to_thread(path.is_file):
            raise StoredObjectMissingError(f"stored object is missing for key {key!r}")

        async def _iterate() -> AsyncIterator[bytes]:
            """Yield the object's bytes, closing the handle when the consumer stops.

            Yields:
                Successive chunks of the stored object.
            """
            handle: BinaryIO = await asyncio.to_thread(path.open, "rb")
            try:
                while True:
                    chunk = await asyncio.to_thread(handle.read, STREAM_CHUNK_SIZE)
                    if not chunk:
                        return
                    yield chunk
            finally:
                await asyncio.to_thread(handle.close)

        return _iterate()

    async def delete(self, key: str) -> None:
        """Remove a stored object, ignoring an already-absent one.

        Args:
            key: The storage key to remove.

        Raises:
            StorageKeyError: If the key is malformed.
        """
        path = self._path_for(key)
        await asyncio.to_thread(path.unlink, True)

    async def exists(self, key: str) -> bool:
        """Report whether an object is present on the filesystem.

        Args:
            key: The storage key to check.

        Returns:
            ``True`` when a regular file exists at the key's path.

        Raises:
            StorageKeyError: If the key is malformed.
        """
        path = self._path_for(key)
        return await asyncio.to_thread(path.is_file)
